# The repository to gather actions metrics from
repository: "gh-metrics"

# The organization that has given repository
organization: "rmiguelac"

timeseriesdb:
  host: localhost
  port: "8086"
  bucket: ghmetrics
  organization: myorg

#report:
#  colors:
#    # RGBA
#    failure: "255, 61, 71, 0.7"
#    success: "139, 193, 71, 0.7"
#  data:
#    last:
#      # months: 1
#      # weeks: 2
#      # days: 5
#      days: 1
#      # hours: 2
